"""timeslots

Revision ID: 3cf7480569d1
Revises: 932607c31832
Create Date: 2018-10-21 15:35:03.357620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cf7480569d1'
down_revision = '932607c31832'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('condition_timeCompare',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['rule'], ['rule.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('condition_timeCompare')
    # ### end Alembic commands ###
